<?php

namespace frontend\base;

use common\models\CartItem;

class Controller extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        $this->view->params['cartItem'] = CartItem::findBySql("
            SELECT SUM(quantity) 
            FROM cart_item 
            WHERE user_id = :user_id",['user_id'=>\Yii::$app->user->id])
            ->scalar();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}