<?php

namespace frontend\base;

use Yii;
use common\models\CartItem;

class Controller extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            $sum = 0;
            $cartItems = Yii::$app->session->get(CartItem::SESSION_KEY, []);

            foreach ($cartItems as &$cartItem) {
                $sum += $cartItem['quantity'];
            }
        } else {
            $sum = CartItem::findBySql("
                SELECT SUM(quantity) 
                FROM cart_item 
                WHERE user_id = :user_id", ['user_id' => \Yii::$app->user->id])
            ->scalar();
        }
        $this->view->params['cartItem'] = $sum;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}