<?php

namespace frontend\base;

use common\models\CartItem;

class Controller extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        $this->view->params['cartItem'] = CartItem::getTotalQuantity(currUserId());
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}